version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ${PWD}/app/build:/usr/share/nginx/html:ro
    environment:
      # - VIRTUAL_HOST=rafaelbm91x.com,www.rafaelbm91x.com
      # - LETSENCRYPT_HOST=rafaelbm91x.com,www.rafaelbm91x.com
      # - LETSENCRYPT_EMAIL=rafaelbm9126x@gmail.com
      - VIRTUAL_HOST=rbm91test.duckdns.org,www.rbm91test.duckdns.org
      - LETSENCRYPT_HOST=rbm91test.duckdns.org,www.rbm91test.duckdns.org
      - LETSENCRYPT_EMAIL=rbm91test@gmail.com

volumes: 
  certs:
  html:
  vhostd:
